name = "caredesk-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
# account_id lido via variavel de ambiente CLOUDFLARE_ACCOUNT_ID

[[d1_databases]]
binding       = "DB"
database_name = "caredesk-sprint"
database_id   = "ecf087ba-7eff-4c80-ac87-5ff72ce6fc46"

[[r2_buckets]]
binding     = "LOGO_BUCKET"
bucket_name = "caredeskstorage"

[vars]
FRONTEND_URL = "https://caredesk-lou.pages.dev"
APP_ENV      = "production"

# Secrets (definir via: wrangler secret put NOME)
# JWT_SECRET
# JWT_REFRESH_SECRET

[triggers]
crons = ["0 11 * * *"]
